name: Debug

on:
  workflow_run:
    workflows: ["Graphql Inspector"]
    types: [completed]

jobs:
  check:
    name: Check Schema
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Dump workflow context
        env:
          COMMIT_SHA: ${{ github.event.workflow_run.head_commit.id }}
          COMMIT_EMAIL: ${{ github.event.workflow_run.head_commit.author.email }}
        run: echo "$COMMIT_SHA - $COMMIT_EMAIL"

