name: Graphql Inspector

on: [push]

jobs:
  check:
    name: Check Schema
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: 'Install'
        run:
          yarn add @graphql-inspector/cli graphql

      - name: 'Test'
        run:
          yarn graphql-inspector diff schema.graphql _schema.graphql

      - uses: ertrzyiks/graphql-inspecto@master
        with:
          name: 'Check Schema'
          schema: 'main:schema.graphql'

